Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Metrics/AbcSize:
  Enabled: true
  Max: 29

Metrics/BlockLength:
  Enabled: true
  Max: 75

Metrics/ClassLength:
  Enabled: true
  Max: 300
  
Metrics/CyclomaticComplexity:  
  Enabled: true
  Max: 10

Metrics/MethodLength:
  Enabled: true
  Max: 60
  
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10  

Naming/MethodParameterName:
  Enabled: false
  
Naming/VariableName:  
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false
