Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Metrics/BlockLength:
  Enabled: true
  Max: 50

Naming/MethodParameterName:
  Enabled: false
  
Naming/VariableName:  
  Enabled: false

Style/CommentedKeyword:
  Enabled: false
